cd "d:/Users/Downloads/k210/demo/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET ALTERAOCLSDKROOT=D:\altera\15.0\hld
SET APPDATA=C:\Users\skb97\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=SKB
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\skb97
SET INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=d:\Users\Downloads\k210\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=d:\Users\Downloads\k210\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=d:\Users\Downloads\k210\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\skb97\AppData\Local\Temp\KendryteIDE_Cache\28911_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LATTICE_INI_PATH=C:\lsc_env
SET LM_LICENSE_FILE=D:\lscc\diamond\3.11_x64\license\license.dat;
SET LOCALAPPDATA=C:\Users\skb97\AppData\Local
SET LOGONSERVER=\\SKB
SET MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
SET NIEXTCCOMPILERSUPP=D:\Program Files\National Instruments\Shared\ExternalCompilerSupport\C\
SET NUMBER_OF_PROCESSORS=12
SET OneDrive=C:\Users\skb97\OneDrive
SET OneDriveConsumer=C:\Users\skb97\OneDrive
SET OS=Windows_NT
SET Path=d:\Users\Downloads\k210\KendryteIDE\bin;d:\Users\Downloads\k210\KendryteIDE\LocalPackage\toolchain\bin;d:\Users\Downloads\k210\KendryteIDE\LocalPackage\cmake\bin;d:\Users\Downloads\k210\KendryteIDE\LocalPackage\jlink;d:\Users\Downloads\k210\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=9e0a
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET QSYS_ROOTDIR=D:\altera\15.0\quartus\sopc_builder\bin
SET QUARTUS_ROOTDIR=D:\altera\15.0\quartus
SET SESSIONNAME=Console
SET SOPC_KIT_NIOS2=D:\altera\15.0\nios2eds
SET ss-root=C:\Program Files (x86)\senseshield\ss
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET SYSTEM_TEMP=C:\Users\skb97\AppData\Local\Temp
SET TEMP=C:\Users\skb97\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\skb97\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\skb97\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=SKB
SET USERDOMAIN_ROAMINGPROFILE=SKB
SET USERNAME=skb97
SET USERPROFILE=C:\Users\skb97
SET VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
SET VSCODE_CWD=C:\WINDOWS\system32
SET VSCODE_IPC_HOOK=\\.\pipe\a6467f6c143c287e4c0f99dababf0468-1.34.1-beta-main-sock
SET VSCODE_LOGS=d:\Users\Downloads\k210\KendryteIDE\UserData\latest\user-data\logs\20201025T014218
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"d:\\Users\\Downloads\\k210\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"d:\\Users\\Downloads\\k210\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"d:\\Users\\Downloads\\k210\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"d:\\Users\\Downloads\\k210\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=d:\Users\Downloads\k210\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=D:\Users\Downloads\k210\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=952
SET VSCODE_PORTABLE=d:\Users\Downloads\k210\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET PYTHONHOME=d:/Users/Downloads/k210/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=d:/Users/Downloads/k210/KendryteIDE/LocalPackage/python2library;d:/Users/Downloads/k210/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"d:/Users/Downloads/k210/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build d:/Users/Downloads/k210/demo/build -- -j 11